name: media-stack

services:
  vpn:
    profiles: [ "vpn" ]
    container_name: vpn
    image: qmcgaw/gluetun:v3.36.0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-nordvpn}
      - OPENVPN_USER=${OPENVPN_USER:-""}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD:-""}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Switzerland}
    networks:
      - media-network
    ports:
      - 5080:5080
      - 6881:6881/tcp
      - 6881:6881/udp
      - 9696:9696
      - 6789:6789
    restart: "unless-stopped"

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - /mnt/torrents:/mnt/torrents
    restart: "unless-stopped"

  nzbget:
    container_name: nzbget
    image: nzbgetcom/nzbget:latest
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - nzbget-config:/config
      - /mnt/usenet:/mnt/usenet
    restart: "unless-stopped"


  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - /mnt:/mnt
    restart: "unless-stopped"

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - /mnt:/mnt
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - bazarr-config:/config
      - /mnt:/mnt
    ports:
      - 6767:6767
    restart: unless-stopped
  
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - media-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - /mnt/media:/mnt/media
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped
  
  nginx:
    image: nginx
    container_name: nginx
    networks:
      media-network:
        ipv4_address: 172.18.0.100
    volumes:
      - nginx-config:/etc/nginx
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  radarr-config:
  sonarr-config:
  bazarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  nginx-config:
  letsencrypt:
  nzbget-config:

networks:
  media-network:
    external: true
